image: mingc/android-build-box:latest

pipelines:
  branches:
    master:
    - step:
        name: Build test
        caches:
        - gradle
        - gradlewrapper
        - androidavd
        script:
        - bash ./gradlew assemble
    staging:
    - step:
        name: Build test
        caches:
        - gradle
        - gradlewrapper
        - androidavd
        script:
        - bash ./gradlew assemble
    dev:
    - step:
        name: Build test
        caches:
        - gradle
        - gradlewrapper
        - androidavd
        script:
        - bash ./gradlew assemble
definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper
    androidavd: $ANDROID_HOME/.android/avd